### ISSUE TITLE
Wrong path in cmake command and the example segfaults

### ISSUE THREAD

**Issue by sujona** [dejunlin/emp#1]
Dear Dejun, I am very interested in you article and this code, and wanted to test if we can use it in a research project. I cloned the repo. First thing: the last line in build_release.sh, looks for the CMakeLists.txt file one level up instead of in the current dir. Thats easy to fix though, and the compilation went smooth. But ./example gives "Segmentation fault (core dumped)" with no further info.

**Comment by dejunlin** [comment]
There is a instruction page I put in the release page documenting how the
codes should be run. There are two parameters you need to give the command
line, e.g., ./example 0.001 0.001, which are the changes in distance (for
forces) and quaternion (for torques) for computing the respective numerical
gradients. I've add a readme file on the front page so that people can see
the instruction.

2017-09-23 7:45 GMT-07:00 sujona <notifications@github.com>:

**Comment by sujona** [comment]
Okay, thanks, that did it. What/where is that "release page" you are referring to?

**Comment by dejunlin** [comment]
It's here: https://github.com/dejunlin/emp/releases

2017-09-24 2:25 GMT-07:00 sujona <notifications@github.com>:
